In [1]:

import numpy as np

Create a null vector of size 10 but the fifth value which is 1.

In [14]:
x=np.zeros(10)
x[5]=1
x


array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [17]:
rows=int(input("Enter the number of rows of the matrix : "))
columns=int(input("Enter the columns of the matrix : "))
x=np.random.random((rows,columns))
print(x)
print(f"Average : {x.mean()}")

[[0.75766983 0.76926986 0.82979582]
 [0.96449202 0.72632419 0.96549348]
 [0.10302022 0.26935365 0.07737973]]
Average : 0.6069776450871097


Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

In [22]:
def T2D(rows,columns):
    x=np.ones((rows,columns))
    x[1:-1,1:-1]=0
    return x

T2D(4,4)

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

Create a vector of size 10 with values ranging from 0 to 1, both excluded.

In [ ]:
np.linspace(0,1,10)[1:-1]

array([0.11111111, 0.22222222, 0.33333333, 0.44444444, 0.55555556,
       0.66666667, 0.77777778, 0.88888889])

 Create a 5x5 matrix with row values ranging from 0 to 4.

In [31]:
k=np.tile(np.arange(5),(5,1))
k

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

 Consider a random integer (in range 1 to 100) vector with shape (10,2) representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

In [47]:
x=np.random.randint(1,101,size=(10,2))
given_point=np.array([2,3])
l=[]
for i in range(0,10):
    r=((x[i][0]-given_point[0])**2 + (x[i][1]-given_point[1])**2)**0.5
    l.append(r)

print("Distance :",l)

Distance : [np.float64(132.94359706281458), np.float64(79.17701686727027), np.float64(53.75872022286245), np.float64(92.65527507918802), np.float64(117.6860229593982), np.float64(41.617304093369626), np.float64(95.13148795220224), np.float64(62.96824596572466), np.float64(80.65358020571685), np.float64(91.59148432032315)]


Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?1

In [51]:
l=np.arange(336).reshape(6,7,8)
n=0
for i in np.nditer(l):
    if i ==100:
        print(n)
    n+=1

100


You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.

Input Format:

A single line of input containing space separated numbers.

Output Format:

Print the reverse NumPy array with type float.

In [ ]:
x=np.array([1,2,3,4,-8,-10])
print(x,sep=" ")
x=x[::-1]
x=x.astype(np.float64)
print(x)

[  1   2   3   4  -8 -10]
[-10.  -8.   4.   3.   2.   1.]


Count the number of elements of a numpy array.

In [4]:
def count(n):
    c=0
    for i in np.nditer(n):
        c+=1
    return c

n=np.array([1,2,3,4,5,6])
print(count(n))
n.size



6


6

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

In [11]:
def softmax(n):
    e=2.77
    if n.ndim==1:
        l=np.exp(n)
        x=np.sum(l)
        return l/x
    else:
        return "This Not 1D array"

n=np.array([33.17344305 ,45.61961654 ,82.05405781 ,80.9647098  ,68.82830233 ,91.52064278])
softmax(n)


array([4.57181033e-26, 1.16249922e-20, 7.73872594e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01])

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.

In [ ]:
def VS(x,y):
    if isinstance(x,np.ndarray) and isinstance(y,np.ndarray):
        return np.vstack((x,y))
    else:
        return "These arrays are not np arrays"
    
x=np.arange(12).reshape(3,4)
y=np.arange(12,24).reshape(3,4)
VS(x,y)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Create a python function named date_array that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: 2022-12-6. The end date should be included and for simplicity, choose dates from a same year.

In [3]:
from datetime import datetime,timedelta
def date_array(s,e):
    l=[]
    s=datetime.strptime(s,"%Y-%m-%d")
    e=datetime.strptime(e,"%Y-%m-%d")
    c=s
    while c<=e:
        l.append(c.strftime("%Y-%m-%d"))
        c+=timedelta(days=1)
    x=np.array(l)
    return x[1:-1]

s="2022-12-6"
e="2022-12-12"
date_array(s,e)

array(['2022-12-07', '2022-12-08', '2022-12-09', '2022-12-10',
       '2022-12-11'], dtype='<U10')

Subtract the mean of each row from a matrix.

In [8]:
x=np.arange(12).reshape(3,4)
mean=x.mean(axis=1,keepdims=True)
x-mean

array([[-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5]])

Swap column-1 of array with column-2 in the array.

In [12]:
x=np.arange(12,24).reshape(3,4)
x[:,[1,2]]=x[:,[2,1]]
x

array([[12, 14, 13, 15],
       [16, 18, 17, 19],
       [20, 22, 21, 23]])

Replace odd elements in arrays with -1.

In [ ]:
x=np.arange(16,32).reshape(4,4)
print(x)
for index,value in np.ndenumerate(x):
    if value%2==1:
        x[index]=-1
x


[[16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([[16, -1, 18, -1],
       [20, -1, 22, -1],
       [24, -1, 26, -1],
       [28, -1, 30, -1]])

Given two arrays of same shape make an array of max out of two arrays. (Numpy way)

In [25]:
a1=np.arange(16).reshape(4,4)
a2=np.arange(16,32).reshape(4,4)
max=np.maximum(a1,a2)
max

array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

Q-18 Answer below asked questions on given array:
Fetch Every alternate column of the array
Normalise the given array

In [30]:
def normalization(x):
    return (x-np.min(x)) / (np.max(x) - np.min(x))

arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
normalization(arr1)
print(arr1[:,::2])

[[9329 6230 1784]
 [1060 7624 7498]
 [ 140 6130 3978]
 [1817 4634 9822]
 [3213 4664  534]
 [ 650 9050 8675]
 [5125 2669 3234]
 [7758 7834 3005]]


Q-19: Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array

In [42]:
def fun(x,i):
    if i<=x.size:
        return x[i]
    else:
        return "Index Out Of The Range "

arr2=np.arange(40,52)
print(arr2)
fun(arr2,7)


[40 41 42 43 44 45 46 47 48 49 50 51]


np.int64(47)

Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [44]:
a=np.array([1,2,3])
p1=np.repeat(a,3)
p2=np.tile(a,3)
result=np.concatenate((p1,p2))
result

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

You're given data for 6 students across 5 subjects. Perform the following tasks using NumPy only.
🔧 Tasks to Perform
🔹 Basic Array Info
Print the array of marks.

Display the shape, size, and data type of the array.

🔹 Statistical Analysis
Find the total, average, minimum, and maximum marks for each student.

Find the average marks per subject.

Identify which student scored the highest overall.

🔹 Normalization
Normalize the marks using min-max normalization for each subject:

normalized
=
𝑥
−
min
⁡
(
𝑥
)
max
⁡
(
𝑥
)
−
min
⁡
(
𝑥
)
normalized= 
max(x)−min(x)
x−min(x)
​
 
🔹 Advanced Operations
Replace any marks < 50 with 50 (pass criteria).

Apply the floor, ceil, and round functions on the array and print all versions.

🔹 Indexing and Slicing
Extract marks of the 3rd and 4th students.

Get marks for only the first 3 subjects across all students.

🔹 Stacking and Splitting
Create a new array with the student IDs (1 to 6) as a column, and horizontally stack it with the original marks array.

Split the resulting array into two arrays: one with student IDs and one with only marks.

🔹 Iteration and Flattening
Iterate over the marks of each student and print them.

Flatten the original marks array using ravel() and calculate mean and std deviation.

In [7]:
np.random.seed(0)
marks=np.random.randint(45,101,size=(6,5))
# Display the shape, size, and data type of the array.
print(marks.shape)
print(marks.size)
print(marks.dtype)

# Find the total, average, minimum, and maximum marks for each student.
print(f"Total : {np.sum(marks)}, Average :{np.mean(marks)}, Minimum :{np.min(marks)} , Maximim : {np.max(marks)}")

#Normalize the marks using min-max normalization for each subject:
def Normalize(x):
    return (x - np.min(x)) / (np.max(x) - np.min(x))

Normalize(marks)



(6, 5)
30
int32
Total : 2063, Average :68.76666666666667, Minimum :45 , Maximim : 98


array([[0.83018868, 0.88679245, 1.        , 0.        , 0.05660377],
       [0.05660377, 0.73584906, 0.16981132, 0.35849057, 0.39622642],
       [0.94339623, 0.67924528, 0.43396226, 0.11320755, 0.45283019],
       [0.45283019, 0.22641509, 0.01886792, 0.71698113, 0.73584906],
       [0.43396226, 0.86792453, 0.45283019, 0.32075472, 0.69811321],
       [0.47169811, 0.24528302, 0.1509434 , 0.16981132, 0.37735849]])

In [13]:
# Replace any marks < 50 with 50 (pass criteria).
for i in range(marks.shape[0]):
    for k in range(marks.shape[1]):
        if marks[i,k]<50:
            marks[i,k]=50
# Alternative 
marks[marks<50]=50
# Apply the floor, ceil, and round functions on the array and print all versions.
print(np.round(marks))
print(np.ceil(marks))
print(np.floor(marks))

[[89 92 98 50 50]
 [50 84 54 64 66]
 [95 81 68 51 69]
 [69 57 50 83 84]
 [68 91 69 62 82]
 [70 58 53 54 65]]
[[89 92 98 50 50]
 [50 84 54 64 66]
 [95 81 68 51 69]
 [69 57 50 83 84]
 [68 91 69 62 82]
 [70 58 53 54 65]]
[[89 92 98 50 50]
 [50 84 54 64 66]
 [95 81 68 51 69]
 [69 57 50 83 84]
 [68 91 69 62 82]
 [70 58 53 54 65]]


In [ ]:
# Extract marks of the 3rd and 4th students
# marks[:1,3:5]
#Get marks for only the first 3 subjects across all students.
marks[:,0:3]


array([[89, 92, 98],
       [50, 84, 54],
       [95, 81, 68],
       [69, 57, 50],
       [68, 91, 69],
       [70, 58, 53]], dtype=int32)

 Create a Scoreboard with Ranking Logic
Generate marks for 10 students in 4 subjects. Then:
Calculate total marks for each student.
Sort students by total marks in descending order.
Assign ranks starting from 1.
Replace ranks for students having equal total marks with the same rank.

In [26]:
np.random.seed(0)
score=np.random.randint(1,101,size=(10,4))
Total=np.sum(score,axis=1)
print(score)
Total

[[ 45  48  65  68]
 [ 68  10  84  22]
 [ 37  88  71  89]
 [ 89  13  59  66]
 [ 40  88  47  89]
 [ 82  38  26  78]
 [ 73  10  21  81]
 [ 70  80  48  65]
 [ 83 100  89  50]
 [ 30  20  20  15]]


array([226, 184, 285, 227, 264, 224, 185, 263, 322,  85])

In [ ]:
score[:,::-1]

array([[ 68,  65,  48,  45],
       [ 22,  84,  10,  68],
       [ 89,  71,  88,  37],
       [ 66,  59,  13,  89],
       [ 89,  47,  88,  40],
       [ 78,  26,  38,  82],
       [ 81,  21,  10,  73],
       [ 65,  48,  80,  70],
       [ 50,  89, 100,  83],
       [ 15,  20,  20,  30]], dtype=int32)

Replace Outliers with Median
Given a random array of exam scores, replace all values more than 2 standard deviations from the mean with the median score.

In [ ]:
mean=np.mean(score)
median=np.median(score)
sd=np.std(score)
score[np.abs(score-mean)>2*sd]=median
score

array([[56, 56, 56, 56],
       [56, 56, 56, 56],
       [56, 56, 56, 56],
       [56, 56, 56, 56],
       [56, 56, 56, 56],
       [56, 56, 56, 56],
       [56, 56, 56, 56],
       [56, 56, 56, 56],
       [56, 56, 56, 56],
       [56, 56, 56, 56]], dtype=int32)

Create a 5x5 matrix where diagonal values go from 1 to 5, and all other values are 0.

In [ ]:
Diagonal=np.zeros((5,5))
for i in range(5):
    Diagonal[i,i]=i+1
Diagonal

array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]])

🔁 7. Generate a Custom Matrix Pattern
Create a 6x6 matrix where:

Border values are 1

Inside values are 0

The diagonal from top-left to bottom-right is filled with 2

In [ ]:
Custom=np.ones((6,6))
Custom
for i in range(1,5):
    Custom[i,i]=2


array([[1., 1., 1., 1., 1., 1.],
       [1., 2., 1., 1., 1., 1.],
       [1., 1., 2., 1., 1., 1.],
       [1., 1., 1., 2., 1., 1.],
       [1., 1., 1., 1., 2., 1.],
       [1., 1., 1., 1., 1., 1.]])

Create a 3×3 matrix and rotate it 90 degrees clockwise and counterclockwise using NumPy (no built-in rotate function allowed).

In [15]:
m=np.arange(1,10).reshape(3,3)
clockwise=np.transpose(m)
print(m)
print(clockwise[:,::-1])

counterclockwise=np.transpose(m)
counterclockwise[::-1]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 4 1]
 [8 5 2]
 [9 6 3]]


array([[3, 6, 9],
       [2, 5, 8],
       [1, 4, 7]])

In [19]:
print(counterclockwise)
counterclockwise[1:3]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


array([[2, 5, 8],
       [3, 6, 9]])

Replace all even numbers with -1.

Find positions of all numbers > 5 and < 8.

In [25]:
arr = np.array([1, 4, 6, 7, 2, 9, 3, 8])
arr[arr %2==0]=-1
arr
position=0
print(arr)
for i,val in enumerate(arr):
    if val>5 and val<8:
        print(f"Position :{i}")

[ 1 -1 -1  7 -1  9  3 -1]
Position :3


Simulate 100 rolls of two dice using np.random.randint():

Count how many times the sum is exactly 7.

Find the most frequent sum.

Show the percentage of times a double (like [2,2] or [5,5]) occurs.

In [ ]:
dice=np.random.randint(1,7,size=(100,2))
l=dice.sum(axis=1)
count=0
for i in np.nditer(l):
    if i==7:
        count+=1
print(f"Sum exactly 7 :{count}")


14


Given a 2D square array A of shape (N, N), extract the anti-diagonal (from top-right to bottom-left) using slicing.

In [ ]:
n=np.random.randint(1,100,16).reshape(4,4)
print(n)
np.fliplr(n).diagonal()

[[98 61  9 26]
 [67 50 61 72]
 [67 21 79 62]
 [ 4  5 93  5]]


array([26, 61, 21,  4], dtype=int32)

Given a 2D array, reverse each row without using a loop.

In [14]:
print(n)
n[::-1,:]

[[98 61  9 26]
 [67 50 61 72]
 [67 21 79 62]
 [ 4  5 93  5]]


array([[ 4,  5, 93,  5],
       [67, 21, 79, 62],
       [67, 50, 61, 72],
       [98, 61,  9, 26]], dtype=int32)

From a 2D array of shape (6,6), extract only the border elements (top row, bottom row, first column, last column) as a 1D array.

In [22]:
print(n)
print(n[[0,3]])
n[1:3,[0,3]]

[[98 61  9 26]
 [67 50 61 72]
 [67 21 79 62]
 [ 4  5 93  5]]
[[98 61  9 26]
 [ 4  5 93  5]]


array([[67, 72],
       [67, 62]], dtype=int32)

Find the nearest element in the array to a given integer.

In [16]:
array=np.random.randint(1,100,56)
print(array)
target=int(input("Enter the target : "))
result=array[np.abs(array-target).argmin()]
print(result)

[15 16 92 24 34  1 44 83 31 52 99 77 11 30 56  1 12 34 55 22  3 85 45 44
 23 61 71 42 67 62 21 66 75 15 68 28  4 28 38 67 20 75 20 85 65 92 46 22
 98 28 43 16 95 38 43 95]
4


In [50]:
import numpy as np

Replace multiples of 3 or 5 as 0 in the given array.

In [8]:
arr=np.array([1,2,3,4,5,6,7,9])
arr[(arr%3==0) | (arr%5==0)]=0
arr

array([1, 2, 0, 4, 0, 0, 7, 0])

Double the array elements at given indexes
indexes = [0,3,4,9]

In [13]:
arr=np.arange(10)
indexes=[0,3,4,9]
print(arr)
arr[indexes]=arr[indexes]*2
arr

[0 1 2 3 4 5 6 7 8 9]


array([ 0,  1,  2,  6,  8,  5,  6,  7,  8, 18])

Using a given array make a different array as in below example

array = [1,2,3]
result array -> [1 1 1 2 2 2 3 3 3]

In [15]:
array=[1,2,3]
result=np.repeat(array,3)
result

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

 Your are given an array which is havig some nan value. You job is to fill those nan values with most common element in the array.

In [26]:
arr=np.array([[1,2,np.nan],[4,2,6],[np.nan,np.nan,5]])
flat=arr.flatten()
flat=flat[~np.isnan(flat)]
values,count=np.unique(flat,return_counts=True)
common=values[np.argmax(count)]
result=np.nan_to_num(arr,nan=common)
result

array([[1., 2., 2.],
       [4., 2., 6.],
       [2., 2., 5.]])

Write a NumPy program
to find the missing data in a given array. Return a boolean matrix.
also try to fill those missing values with 0. For that, you can use np.nan_to_num(a)


In [29]:
array=np.array([[3, 2, np.nan, 1],
          [10, 12, 10, 9],
          [5, np.nan, 1, np.nan]])
print(np.isnan(array))
array=np.nan_to_num(array)
array

[[False False  True False]
 [False False False False]
 [False  True False  True]]


array([[ 3.,  2.,  0.,  1.],
       [10., 12., 10.,  9.],
       [ 5.,  0.,  1.,  0.]])

Create a random 3x4 matrix with value between 0-100. And perform below tasks
i. Sort this matrix. np.sort()
ii. Sort this matrix based on values in 2nd column.
iii. Sort this matrix based on max value in each row.
iv. Sort based on elements value.

In [54]:
np.random.seed(0)
r=np.random.randint(0,100,(3,4))
print(r)
np.sort(r,axis=1)
result=r[r[:,1].argsort()]
result

[[44 47 64 67]
 [67  9 83 21]
 [36 87 70 88]]


array([[67,  9, 83, 21],
       [44, 47, 64, 67],
       [36, 87, 70, 88]], dtype=int32)

In [64]:
print(r)
m=np.max(r,axis=1)
sorted=r[np.argsort(m)]
sorted

[[44 47 64 67]
 [67  9 83 21]
 [36 87 70 88]]


array([[44, 47, 64, 67],
       [67,  9, 83, 21],
       [36, 87, 70, 88]], dtype=int32)

 There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.

i. Add marks every student of an extra subject in the same array.

ii. Add two new students marks in respective 5 subjects.(one subject added in above task)

iii. Add extra column with sum of all subjects(5-subjects) marks

iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.