In [1]:
import numpy as np
l=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(l[1][4])
l.shape

10


(2, 5)

In [16]:
a=np.array([[[1,2]],[[3,4]]])
a.shape

(2, 1, 2)

In [2]:
b=np.array([{38:"Jon",61:"Alex",93:"Adam"},{85:"Buttler",33:"Smith",81:"Ben"}],dtype=dict)
b

array([{38: 'Jon', 61: 'Alex', 93: 'Adam'},
       {85: 'Buttler', 33: 'Smith', 81: 'Ben'}], dtype=object)

In [2]:
import numpy as np
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.random.random((2,5))

array([[0.36623091, 0.61580691, 0.88010522, 0.44083829, 0.49979197],
       [0.06390526, 0.12469889, 0.03643677, 0.16715858, 0.92743179]])

In [11]:
np.linspace(-100,100,10)

array([-100.        ,  -77.77777778,  -55.55555556,  -33.33333333,
        -11.11111111,   11.11111111,   33.33333333,   55.55555556,
         77.77777778,  100.        ])

In [12]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
n=np.arange(16).reshape(4,4)
print(n)
n[0:2,1:4]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[1, 2, 3],
       [5, 6, 7]])

In [6]:
n=np.arange(27).reshape(3,3,3)
print(n)
# n[1,::,::]
# n[2,1:3,1:3]
n[::2,0,::2]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[ 0,  2],
       [18, 20]])

In [16]:
n.ndim

4

In [17]:
n.shape

(2, 2, 2, 2)

In [18]:
n.size

16

In [ ]:
n.itemsize

8

In [22]:
n.dtype

dtype('int64')

In [28]:
n=n.astype(np.int32)
n.dtype

dtype('int32')

In [ ]:
a=np.array([[1],[4],[7]])
b=np.array([1,2,3])
b+a


array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
x=np.random.random((3,3))
x=np.round(x*100)
x

array([[89., 16.,  5.],
       [37., 94., 19.],
       [19., 14., 24.]])

In [22]:
np.max(x)

np.float64(94.0)

In [23]:
np.min(x)

np.float64(5.0)

In [ ]:
np.sum(x)

array([110., 150.,  57.])

In [27]:
np.prod(x)

np.float64(3003696514560.0)

In [35]:
x[2][1]=56
x

array([[89., 16.,  5.],
       [37., 94., 19.],
       [19., 56., 24.]])

In [ ]:
np.max(x,axis=0)

array([89., 94., 24.])

In [43]:
np.mean(x,axis=1)

array([36.66666667, 50.        , 33.        ])

In [47]:
np.median(x,axis=1)

array([16., 37., 24.])

In [48]:
np.std(x)

np.float64(30.76955365452618)

In [49]:
np.var(x)

np.float64(946.7654320987654)

In [ ]:
np.sin(x)

array([[ 0.86006941, -0.28790332, -0.95892427],
       [-0.64353813, -0.24525199,  0.14987721],
       [ 0.14987721, -0.521551  , -0.90557836]])

In [2]:
x=np.random.random((3,3))
y=np.array([[10,11,12],[13,14,15]])
if y.shape[0]==x.shape[1]:
    print("Yes both of these matrics are eligble for dot product ")
else:
    print("No both of these matrics are not eligble for dot product ")


No both of these matrics are not eligble for dot product 


In [1]:
import numpy as np


In [6]:
np.round(x)

array([[64., 15., 94.],
       [50., 61., 69.],
       [13., 48., 74.]])

In [7]:
np.floor(x)

array([[64., 15., 94.],
       [50., 61., 69.],
       [13., 48., 74.]])

In [8]:
np.ceil(x)

array([[64., 15., 94.],
       [50., 61., 69.],
       [13., 48., 74.]])

In [8]:
for i in np.nditer(n):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [16]:
y=np.arange(12).reshape(3,4)
z=np.arange(24,36).reshape(3,4)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
y.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [13]:
y.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
k=np.hstack((y,z))

In [18]:
np.vstack((z,y))

array([[24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
np.hsplit(k,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]])]

In [ ]:
np.vsplit(k,3)

[array([[ 0,  1,  2,  3, 24, 25, 26, 27]]),
 array([[ 4,  5,  6,  7, 28, 29, 30, 31]]),
 array([[ 8,  9, 10, 11, 32, 33, 34, 35]])]

Fancy Indexing

In [ ]:
x=np.arange(24).reshape(6,4)
print(x)
x[3:7,[1,2,3]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[13, 14, 15],
       [17, 18, 19],
       [21, 22, 23]])

Boolean Indexing

In [17]:
h=np.random.randint(1,101,24).reshape(6,4)
h[(h%2==0) & (h>50)]

array([60, 98, 70, 78, 88, 86, 96, 80], dtype=int32)

In [15]:
h[h % 7!=0]

array([ 44,  30,  85,  52,  51,  82,  73,  18,   4,  95,  30,  66,  61,
        90,  20,  50,  96,  87,  71, 100], dtype=int32)

In [2]:
import numpy as np

Numpy Functions

In [3]:
np.random.seed(0)
n1=np.random.randint(1,101,60)
n2=np.random.randint(101,201,60).reshape(6,10)
print(n1)
n2

[ 45  48  65  68  68  10  84  22  37  88  71  89  89  13  59  66  40  88
  47  89  82  38  26  78  73  10  21  81  70  80  48  65  83 100  89  50
  30  20  20  15  40  33  66  10  58  33  32  75  24  36  76  56  29  35
   1   1  37  54   6  39]


array([[118, 180, 105, 143, 159, 132, 102, 166, 142, 158],
       [136, 112, 147, 183, 192, 101, 115, 200, 154, 113],
       [143, 185, 176, 169, 107, 169, 148, 104, 177, 153],
       [179, 116, 121, 200, 159, 124, 180, 114, 186, 149],
       [150, 170, 142, 136, 165, 196, 170, 195, 101, 151],
       [137, 135, 149, 194, 104, 199, 143, 178, 122, 174]], dtype=int32)

In [25]:
np.sort(n2,axis=0)

array([[118, 112, 105, 136, 104, 101, 102, 104, 101, 113],
       [136, 116, 121, 143, 107, 124, 115, 114, 122, 149],
       [137, 135, 142, 169, 159, 132, 143, 166, 142, 151],
       [143, 170, 147, 183, 159, 169, 148, 178, 154, 153],
       [150, 180, 149, 194, 165, 196, 170, 195, 177, 158],
       [179, 185, 176, 200, 192, 199, 180, 200, 186, 174]], dtype=int32)

In [10]:
np.append(n1,100)
np.append(n2,np.ones((6,1)),axis=1)

array([[118., 180., 105., 143., 159., 132., 102., 166., 142., 158.,   1.],
       [136., 112., 147., 183., 192., 101., 115., 200., 154., 113.,   1.],
       [143., 185., 176., 169., 107., 169., 148., 104., 177., 153.,   1.],
       [179., 116., 121., 200., 159., 124., 180., 114., 186., 149.,   1.],
       [150., 170., 142., 136., 165., 196., 170., 195., 101., 151.,   1.],
       [137., 135., 149., 194., 104., 199., 143., 178., 122., 174.,   1.]])

In [3]:
n3=np.random.randint(1000,2001,60).reshape(6,10)
np.concatenate((n2,n3),axis=1)

array([[ 118,  180,  105,  143,  159,  132,  102,  166,  142,  158, 1383,
        1512, 1906, 1370, 1555, 1954, 1383, 1023, 1699, 1130],
       [ 136,  112,  147,  183,  192,  101,  115,  200,  154,  113, 1377,
        1098, 1574, 1931, 1734, 1123, 1963, 1594, 1942, 1739],
       [ 143,  185,  176,  169,  107,  169,  148,  104,  177,  153, 1148,
        1209, 1562, 1411, 1782, 1041, 1058, 1705, 1036, 1778],
       [ 179,  116,  121,  200,  159,  124,  180,  114,  186,  149, 1086,
        1043, 1872, 1011, 1770, 1307, 1080, 1032, 1182, 1128],
       [ 150,  170,  142,  136,  165,  196,  170,  195,  101,  151, 1806,
        1275, 1174, 1554, 1371, 1184, 1444, 1488, 1589, 1286],
       [ 137,  135,  149,  194,  104,  199,  143,  178,  122,  174, 1280,
        1637, 1770, 1515, 1094, 1226, 1875, 1269, 1880, 1296]],
      dtype=int32)

In [4]:
arr=np.array([1,2,2,3,4,4,5])
arr2=np.array([[1,2,3,3],[4,5,6,6]])
print(np.unique(arr))
np.unique(arr2)

[1 2 3 4 5]


array([1, 2, 3, 4, 5, 6])

In [ ]:
result=np.expand_dims(arr,axis=1)
print(arr.shape)
result.shape

(7,)


(7, 1)

In [28]:
np.where(n2%2==0,n2,1)

array([[118, 180,   1,   1,   1, 132, 102, 166, 142, 158],
       [136, 112,   1,   1, 192,   1,   1, 200, 154,   1],
       [  1,   1, 176,   1,   1,   1, 148, 104,   1,   1],
       [  1, 116,   1, 200,   1, 124, 180, 114, 186,   1],
       [150, 170, 142, 136,   1, 196, 170,   1,   1,   1],
       [  1,   1,   1, 194, 104,   1,   1, 178, 122, 174]], dtype=int32)

In [30]:
np.argmax(n3,axis=1)

array([7, 1, 9, 1, 6, 0])

In [ ]:
np.argmin(n3,axis=0) 

array([3, 2, 2, 0, 4, 0, 0, 3, 1, 1])

In [ ]:
np.cumsum(arr)

array([ 1,  3,  5,  8, 12, 16, 21])

In [34]:
n3

array([[1735, 1886, 1812, 1216, 1381, 1024, 1067, 1978, 1771, 1234],
       [1716, 1998, 1291, 1726, 1701, 1709, 1727, 1555, 1032, 1011],
       [1616, 1212, 1138, 1694, 1421, 1637, 1668, 1623, 1488, 1770],
       [1539, 1979, 1217, 1663, 1821, 1307, 1174, 1148, 1949, 1541],
       [1579, 1547, 1807, 1393, 1073, 1297, 1919, 1899, 1814, 1730],
       [1946, 1876, 1771, 1799, 1777, 1394, 1539, 1429, 1199, 1423]],
      dtype=int32)

In [35]:
np.cumsum(n3,axis=1)

array([[ 1735,  3621,  5433,  6649,  8030,  9054, 10121, 12099, 13870,
        15104],
       [ 1716,  3714,  5005,  6731,  8432, 10141, 11868, 13423, 14455,
        15466],
       [ 1616,  2828,  3966,  5660,  7081,  8718, 10386, 12009, 13497,
        15267],
       [ 1539,  3518,  4735,  6398,  8219,  9526, 10700, 11848, 13797,
        15338],
       [ 1579,  3126,  4933,  6326,  7399,  8696, 10615, 12514, 14328,
        16058],
       [ 1946,  3822,  5593,  7392,  9169, 10563, 12102, 13531, 14730,
        16153]])

In [36]:
np.cumprod(arr)

array([  1,   2,   4,  12,  48, 192, 960])

In [39]:
print(n1)
np.percentile(n1,99)

[ 45  48  65  68  68  10  84  22  37  88  71  89  89  13  59  66  40  88
  47  89  82  38  26  78  73  10  21  81  70  80  48  65  83 100  89  50
  30  20  20  15  40  33  66  10  58  33  32  75  24  36  76  56  29  35
   1   1  37  54   6  39]


np.float64(93.50999999999996)

In [42]:
print(n1.shape)
np.histogram(n1,bins=[0,25,50,75,100])

(60,)


(array([13, 18, 14, 15]), array([  0,  25,  50,  75, 100]))

In [6]:
np.corrcoef(n2,n3)  

array([[ 1.00000000e+00,  2.54900032e-01, -1.92971222e-01,
        -3.24582817e-01,  1.86162744e-01, -8.14360628e-03,
        -3.96977415e-01, -2.34083804e-01,  4.00384573e-01,
        -2.60775528e-01, -1.17376405e-01, -4.04457027e-01],
       [ 2.54900032e-01,  1.00000000e+00, -5.94279822e-01,
         1.64086596e-01, -1.24133689e-01, -1.28374681e-01,
        -3.04060520e-01,  4.38270560e-01,  5.38255179e-01,
         1.84202950e-01,  3.51259400e-01, -2.37149491e-01],
       [-1.92971222e-01, -5.94279822e-01,  1.00000000e+00,
         4.80887830e-02, -4.41827806e-01,  1.51191526e-01,
         5.46653013e-01, -1.98016438e-01, -5.61726983e-01,
        -9.48935061e-02, -2.53127569e-01,  6.17964346e-01],
       [-3.24582817e-01,  1.64086596e-01,  4.80887830e-02,
         1.00000000e+00, -6.27059552e-01, -1.81772601e-01,
        -1.35184973e-01,  6.88594592e-01, -2.86047375e-01,
        -2.63135713e-01,  6.89175163e-01,  2.26710316e-01],
       [ 1.86162744e-01, -1.24133689e-01, -4.4182780

In [8]:
print(arr)
np.isin(arr,4)

[1 2 2 3 4 4 5]


array([False, False, False, False,  True,  True, False])

In [9]:
print(arr)
np.flip(arr)

[1 2 2 3 4 4 5]


array([5, 4, 4, 3, 2, 2, 1])

In [11]:
print(n2)
np.flip(n2)

[[118 180 105 143 159 132 102 166 142 158]
 [136 112 147 183 192 101 115 200 154 113]
 [143 185 176 169 107 169 148 104 177 153]
 [179 116 121 200 159 124 180 114 186 149]
 [150 170 142 136 165 196 170 195 101 151]
 [137 135 149 194 104 199 143 178 122 174]]


array([[174, 122, 178, 143, 199, 104, 194, 149, 135, 137],
       [151, 101, 195, 170, 196, 165, 136, 142, 170, 150],
       [149, 186, 114, 180, 124, 159, 200, 121, 116, 179],
       [153, 177, 104, 148, 169, 107, 169, 176, 185, 143],
       [113, 154, 200, 115, 101, 192, 183, 147, 112, 136],
       [158, 142, 166, 102, 132, 159, 143, 105, 180, 118]], dtype=int32)

In [ ]:
np.put(arr,[0,1],[101,500])
arr

array([101, 500,   2,   3,   4,   4,   5])

In [11]:
print(arr)
print(np.delete(arr,0))
print(n2)
np.delete(n2,[0,1,5,6])

[101 500   2   3   4   4   5]
[500   2   3   4   4   5]
[[118 180 105 143 159 132 102 166 142 158]
 [136 112 147 183 192 101 115 200 154 113]
 [143 185 176 169 107 169 148 104 177 153]
 [179 116 121 200 159 124 180 114 186 149]
 [150 170 142 136 165 196 170 195 101 151]
 [137 135 149 194 104 199 143 178 122 174]]


array([105, 143, 159, 166, 142, 158, 136, 112, 147, 183, 192, 101, 115,
       200, 154, 113, 143, 185, 176, 169, 107, 169, 148, 104, 177, 153,
       179, 116, 121, 200, 159, 124, 180, 114, 186, 149, 150, 170, 142,
       136, 165, 196, 170, 195, 101, 151, 137, 135, 149, 194, 104, 199,
       143, 178, 122, 174], dtype=int32)

In [12]:
np.union1d(n1,arr)

array([  1,   2,   3,   4,   5,   6,  10,  13,  15,  20,  21,  22,  24,
        26,  29,  30,  32,  33,  35,  36,  37,  38,  39,  40,  45,  47,
        48,  50,  54,  56,  58,  59,  65,  66,  68,  70,  71,  73,  75,
        76,  78,  80,  81,  82,  83,  84,  88,  89, 100, 101, 500])

In [13]:
np.intersect1d(arr,n1)

array([], dtype=int64)

In [14]:
np.setdiff1d(n1,arr)

array([  1,   6,  10,  13,  15,  20,  21,  22,  24,  26,  29,  30,  32,
        33,  35,  36,  37,  38,  39,  40,  45,  47,  48,  50,  54,  56,
        58,  59,  65,  66,  68,  70,  71,  73,  75,  76,  78,  80,  81,
        82,  83,  84,  88,  89, 100], dtype=int32)

In [15]:
np.setxor1d(arr,n1)

array([  1,   2,   3,   4,   5,   6,  10,  13,  15,  20,  21,  22,  24,
        26,  29,  30,  32,  33,  35,  36,  37,  38,  39,  40,  45,  47,
        48,  50,  54,  56,  58,  59,  65,  66,  68,  70,  71,  73,  75,
        76,  78,  80,  81,  82,  83,  84,  88,  89, 100, 101, 500])

In [23]:
print(arr)
np.clip(arr,min=3,max=5)

[101 500   2   3   4   4   5]


array([5, 5, 3, 3, 4, 4, 5])

In [2]:
x=9
y=3.0
print(x+y)

12.0
